const WishlistActionTypes = {
  TOGGLE_MESSAGE_HIDDEN: 'TOGGLE_MESSAGE_HIDDEN',
  TOGGLE_WISHLIST: 'TOGGLE_WISHLIST',
  REMOVE_WISHLIST: 'REMOVE_WISHLIST',
  CLEAR_WISHLIST: 'CLEAR_WISHLIST',
  RESTORE_WISHLIST: 'RESTORE_WISHLIST'
}

export default WishlistActionTypes;